name: Sync Wiki

on:
  push:
    paths:
      - 'Catalogue Plotting/Code/wikipages/**'
    branches:
      - main
  workflow_dispatch: 
jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Clone wiki repo
        run: |
          git clone "https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository_owner }}/$(basename ${{ github.repository }}).wiki.git" wiki

      - name: Copy markdown files
        run: |
          rm -rf wiki/*
          cp -r "Catalogue Plotting/Code/wikipages/." wiki/

      - name: Rename markdown files based on Summary content
        run: |
          # Loop through all markdown files in the wiki directory
          for file in wiki/*.md; do
            # Find the line starting with '## Summary:' and extract everything after it
            summary=$(grep -m 1 '^## Summary:' "$file" | sed 's/^## Summary: //')

            # Check if the summary line is non-empty
            if [ -n "$summary" ]; then
              # Clean up the summary to use it as a filename (replace spaces with underscores)
              new_name=$(echo "$summary" | tr '[:space:]' '_')
              # Remove leading and trailing spaces from the new filename
              new_name=$(echo "$new_name" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
              mv "$file" "wiki/${new_name}.md"
            fi
          done

      - name: Push to wiki
        run: |
          cd wiki
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update wiki pages" || echo "No changes to commit"
          git push
