name: Sync Wiki

on:
  push:
    paths:
      - 'pages/**'
    branches:
      - main
  workflow_dispatch: 

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Clone wiki repo
        run: |
          git clone "https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository_owner }}/$(basename ${{ github.repository }}).wiki.git" wiki

      - name: Copy wiki base and all markdown pages (flattened)
        run: |
          rm -rf wiki/*
          # Copy all markdown files from base folder
          cp pages/base/*.md wiki/ || true
          # Copy markdown files from all other subfolders (flattened)
          find pages -type f -name "*.md" ! -path "pages/base/*" -exec cp {} wiki/ \;

      - name: Push to wiki
        run: |
          cd wiki
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update wiki pages" || echo "No changes to commit"
          git push
